log_file: 'out/single/maskInit_noTrain_origFunc.txt'
device: '1'
property_map: 'property_map.json'
property_prompt_cp: 'out/single/maskInit_noTrain_origFunc.pt'
propertyInit: false

# Training setting
iter: 0
train: 'webnlg_dataset/single/award/Train.jsonl'
dev: 'webnlg_dataset/single/award/Dev.jsonl'
num_cand: 10
accumulation_steps: 1
model_name: 'facebook/bart-base'
bsz: 10
eval_size: 5
tokenize_labels: true
filter: true
print_lama: true
seed: 0
debug: true